### ISSUE TITLE
Add support for DECIMAL type

### ISSUE THREAD

**Issue by shun0102** [embulk/embulk-input-jdbc#1]
It seems DECIMAL data types are not supported.
DECIMAL type cause this error.

  org/embulk/input/jdbc/getter/ColumnGetterFactory.java:94:in `unsupportedOperationException': java.lang.UnsupportedOperationException: Unsupported type DECIMAL (sqlType=3)

**Comment by frsyuki** [comment]
Do you think converting SQL's DECIMAL to Embulk's double is acceptable?

**Comment by shun0102** [comment]
Yes, I think so.

**Comment by frsyuki** [comment]
Thank you! Merged.

**Comment by frsyuki** [comment]
I released v0.2.1 with this fix.
