### ISSUE TITLE
[MySQL] utf8mb4 support

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-input-jdbc#114]
A user wants to use utf8mb4 character encoding. 
https://twitter.com/yukiyan_w/status/878067988749991937 (written in Japanese)

Connector/J 5.1.42 add support `utf8mb4` character encoding. 

> Added Japanese collation for the utf8mb4 character set.

https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-42.html

**Comment by hito4t** [comment]
Will #116 solve the issue?

**Comment by hiroyuki-sato** [comment]
Thank you!. I'll try this later.

**Comment by y-ken** [comment]
I think It need to update bundled jar file.

**Comment by y-ken** [comment]
Thank you!
It seems done, don't you?

**Comment by hiroyuki-sato** [comment]
@y-ken You are right. I close this case. Thank you.
