### ISSUE TITLE
The constructor of `org.embulk.spi.time.TimestampFormatter` has been deprecated in Embulk 0.8.29. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-input-jdbc#118]
The constructor of org.embulk.spi.time.TimestampFormatter has been deprecated in Embulk 0.8.29.

https://gist.github.com/k0uki/63a6fbdee7b5c67f83fea36a0714b09b

**Comment by dmikurube** [comment]
My ideas are to:

1. Ignore the deprecation warnings for a while. They're just "deprecated" for the time being. Removing them would be after a long interval.

OR

2. Call `TimestampFormatter(Task task, Optional<? extends TimestampColumnOption> columnOption)` instead for a while. This constructor has been used for a long time. `TimestampFormatter(String format, DateTimeZone timeZone)` is "finally" recommended after some reasonable interval, though.
