### ISSUE TITLE
Double values without scientific notation (E)

### ISSUE THREAD

**Issue by cosmok** [embulk/embulk-input-jdbc#123]
Hi,

I am reading from a MySQL DB and outputting into a file,

YML looks something like this:

in:
  type: mysql
  query: SELECT "int_col" FROM table;
  column_options:
    int_col: {type: double}
 
out:
  type: file

And I am noticing that some results in the output file are in scientific notation (for example: 6.097E7).
I can use long (as the type) here as I want whole numbers only, but, would like to know if there are other options.

**Comment by hito4t** [comment]
Hi,
Unfortunately I don't know how to avoid scientific notation with embulk and embulk-input-mysql.
I think you should write a plugin that convert double value to string.
(or someone may have created such a plugin.)

**Comment by hiroyuki-sato** [comment]
Hello, @cosmok 

Workaround: How about cast `decimal` with `query` parameter?


```
mysql> select * from sci ;
+----+--------+
| id | val    |
+----+--------+
|  1 | 1.5e15 |
+----+--------+
1 row in set (0.00 sec)

select * from sci ;
+----+--------+
| id | val    |
+----+--------+
|  1 | 1.5e15 |
+----+--------+
1 row in set (0.00 sec)

select id,cast(val as decimal(65,0)) from sci ;
+----+----------------------------+
| id | cast(val as decimal(65,0)) |
+----+----------------------------+
|  1 |           1500000014041088 |
+----+----------------------------+
```

**Comment by cosmok** [comment]
Thanks @hiroyuki-sato for your suggestion, I will give that a try.
And, thanks hito4t for your reply.
