### ISSUE TITLE
support for clickhouse

### ISSUE THREAD

**Issue by cmdares** [embulk/embulk-input-jdbc#147]
support for clickhouse  input and output.
regard!
thanks!

**Comment by hiroyuki-sato** [comment]
Hello, @cmdares 

Have you ever tried embulk-input-jdbc with [ClickHouse JDBC](https://mvnrepository.com/artifact/ru.yandex.clickhouse/clickhouse-jdbc)?

If that plugin doesn't work as expected, Someone needs to develop a plugin for ClickHouse JDBC.

**Comment by tac0x2a** [comment]
Hello, @cmdares and @hiroyuki-sato . 

First, I tried using ClickHouse JDBC on embulk-input-jdbc, it does NOT work in current implementation. 
So, I sent [pull request to clickhouse-jdbc](https://github.com/yandex/clickhouse-jdbc/pull/238). It will work on embulk-input-jdbc for simple data types if this PR are merged. 

Second, I thought ClickHouse [data types](https://clickhouse.yandex/docs/en/data_types/) need to support by embulk-input-clickhouse plugin. Then, I tried simple simple implementation and send [PR](https://github.com/embulk/embulk-input-jdbc/pull/149) .

I'm verry happy if we review this PR and improve implementation.

**Comment by hiroyuki-sato** [comment]
Hello, @cmdares 
JFYI, @tac0x2a has developed [embulk-input-clickhouse](https://rubygems.org/gems/embulk-input-clickhouse)

Thank you @tac0x2a !

**Comment by tac0x2a** [comment]
Hi, @cmdares 
Today, I fixed plugin to use just install it.
```
$ embulk gem install embulk-input-clickhouse
```
Could you try this ?

@hiroyuki-sato san
I really appreciate your support!

**Comment by sakama** [comment]
Let me close this issue.
Since [embulk-input-clickhouse](https://github.com/tac0x2a/embulk-input-clickhouse) was released.

**Comment by cmdares** [comment]
Hi, @tac0x2a @frsyuki 
thanks for the works! And there is another requirement.
https://github.com/embulk/embulk-output-jdbc/issues/245
to support clickhouse output.
Because of there are many engines, especially the merge family, there are some considerations for writing speed.It is estimated that there will be more considerations.
So still want to give attention and support!
thanks! regard!
