### ISSUE TITLE
require close()? after finish()

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-input-jdbc#187]
@hito4t, @dmikurube 

What do you think about [this comment](https://github.com/embulk/embulk/issues/1218#issuecomment-586336178)?
Please take a look when you get a chance.

> The problem could be in https://github.com/embulk/embulk-input-jdbc/blob/master/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/AbstractJdbcInputPlugin.java#L510 only calls `finish()` that flushes but not releases the buffer (`close()` is also needed). Can you please check?

@shroman  Thank you for your investigation.

**Comment by dmikurube** [comment]
IIRC, it has happened not only JDBC plugins. There may be problems on the plugin side, but if it is happening in many plugins, we may have to consider some work on the core side.

We'll need to have a survey over some major plugins, and decide "how it should be" both on the core and plugins. We may finally conclude we should fix all plugins which have this issue, but TBD.

At least, I don't think we would keep discussing here in `embulk-input-jdbc` unless this happens only in `embulk-input-jdbc`.

**Comment by hiroyuki-sato** [comment]
@dmikurube, Thank you for your reply.

My point is that whether `close()` require after finish() or not.
(Does this behavior "how it should be" issue?)

I think this change can't fix `LEAK: ByteBuf.release()` issue.
Because it doesn't `embulk-input-jdbc` specific issue.

I filed this issue for another(except `LEAK: ByteBuf.release()`) issue.

**Comment by hiroyuki-sato** [comment]
Thank you @dmikurube 

Ref: https://twitter.com/dmikurube/status/1275393589070057474?s=20
