### ISSUE TITLE
zero datetime error

### ISSUE THREAD

**Issue by shun0102** [embulk/embulk-input-jdbc#2]
If DATE or DATETIME columns have zero value, it cause this error.
com/google/common/base/Throwables.java:160:in `propagate': java.lang.RuntimeException: java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date

It will resolved by adding zeroDateTimeBehavior=convertToNull to the connection URI.

**Comment by frsyuki** [comment]
Thank you for reporting!
