### ISSUE TITLE
the parameter timezone doesnt works

### ISSUE THREAD

**Issue by yester354** [embulk/embulk-input-jdbc#20]
Hi
     I encounter a problem . the data display in normal date in my database .but less eight hours displayed by  embulk  even if i set the parameter timezone in .yml file. i had tried to set different value to timezone. it always display the same output
   in my database:
   SQL> select * from sync.ac;

       COL INDATE
---------- -----------------
         1 20150826 10:46;07
         7 20150827 15:47;40
         3 20150826 15:20;24
         4 20150826 15:20;31
         2 20150826 12:54;20
         5 20150826 16:29;15
         6 20150827 10:22;02

7 rows selected.

 in embulk preview
[root@databus embulk-master]# embulk preview config.yml.liquid 
2015-08-27 17:10:34.473 +0800: Embulk v0.7.2
2015-08-27 17:10:35.918 +0800 [INFO] (preview): Loaded plugin embulk-input-oracle (0.6.0)
2015-08-27 17:10:36.326 +0800 [INFO] (preview): SQL: select * from sync.ac where indate>(case when (select max(indate) from flume.ac@embulk) is null then sysdate-36500 when ((select max(indate) from sync.ac)=(select max(indate) from flume.ac@embulk)) then sysdate+1 else (select max(indate) from flume.ac@embulk)  end)

2015-08-27 17:10:36.365 +0800 [INFO] (preview): > 0.04 seconds
+------------+-------------------------+
| COL:double |        INDATE:timestamp |
+------------+-------------------------+
|        1.0 | 2015-08-26 02:46:07 UTC |
|        7.0 | 2015-08-27 07:47:40 UTC |
|        3.0 | 2015-08-26 07:20:24 UTC |
|        4.0 | 2015-08-26 07:20:31 UTC |
|        2.0 | 2015-08-26 04:54:20 UTC |
|        5.0 | 2015-08-26 08:29:15 UTC |
|        6.0 | 2015-08-27 02:22:02 UTC |
+------------+-------------------------+
[root@databus embulk-master]# 

my .yml file as below:
in:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.56
  user: sync
  password: m123
  database: oggmysql
  query: |
        select * from sync.ac where indate>(case when (select max(indate) from flume.ac@embulk) is null then sysdate-36500 when ((select max(indate) from sync.ac)=(select max(indate) from flume.ac@embulk)) then sysdate+1 else (select max(indate) from flume.ac@embulk)  end)
  column_options:
       indate: {type: string, timezone: "+0800"}
out:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.57
  user: flume
  password: m123
  database: embulk
  table: AC
  mode: insert
  insert_method: normal
  columns_options:
    indate :{type : date}

i had tried to set timezone to "+0800" and "+0000" .but it doesn't work .the output of the embulk preview remain the same.

**Comment by hito4t** [comment]
Hi
Date values in Oracle don't have timezone.
embulk-input-oracle always select date values in the default timezone in your environment (not use `timezone` in yml yet).
Namely, `2015-08-26 10:46:07` in Oracle is `2015-08-26 10:46:07 +800` in Embulk.
And it is equal to `2015-08-26 02:46:07 UTC`.

Do you want to get `2015-08-26 10:46:07 UTC`, or output `2015-08-26 10:46:07 +800`?

**Comment by yester354** [comment]
Hi
   i want to get 2015-08-26 10:46:07 +800.when i load data from oracle to oracle .i find that the date in target table is different from the source table . so i try to find the reason.all the timezone setting are the same in both oracle database.at last i find  it was caused by embulk's timezone.so i want embulk to get the output like 2015-08-26 10:46:07 +800 .
thanks for you replay

**Comment by hito4t** [comment]
Hi
By default, embulk-input-jdbc select date values in timezone of the environment.
By default, embulk-output-jdbc insert date values in UTC.
This causes the problem.

You can load correct values by setting `default_timezone` of embulk-output-oracle.
<pre>
out:
    type: oracle
    ...
    default_timezone: "+0800"
</pre>

We will correct the problem.

Thanks

**Comment by yester354** [comment]
Hi 
  I add default_timezone parameter to the out section.but it seem doesnt work.my .yml file as below
in:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.56
  user: sync
  password: m123
  database: oggmysql
  query: |
    select * from sync.ac where indate>(case when (select max(indate) from flume.ac@embulk) is null then sysdate-36500 when ((select max(indate) from sync.ac)=(select max(indate) from flume.ac@embulk)) then sysdate+1 else (select max(indate) from flume.ac@embulk)  end)
out:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.57
  user: flume
  password: m123
  database: embulk
  table: AC
  mode: insert
  defalut_timezone: "+0800"
  insert_method: direct

 source database:
 SQL> select * from sync.ac where col=9;

       COL INDATE
---------- -----------------
         9 20150828 10:21:19

SQL> 

target database:

SQL>  select * from flume.ac where col=9;

       COL INDATE
---------- -----------------
         9 20150828 02:21:19
         9 20150828 02:21:19
         9 20150828 02:21:19

SQL> 

in target database. i tried three times.

**Comment by hito4t** [comment]
Hi
> defalut_timezone: "+0800"

`defalut` is misspelled.

**Comment by yester354** [comment]
Hi 
   i am sorry that i make such a  mistake.now it ok.thanks very much

**Comment by Eruhanu** [comment]
Hi,

I have a problem. In Turkey, we use +0300 in summers and +0200 in winters. When I type defalut_timezone: "+0300" in output part, I get wrong data which is dated in winters which we use +0200. Is there a way to get rid of this situation? Is there a way to take data what ever it is, without changing time zone?

Thanks for helping

**Comment by hito4t** [comment]
@Eruhanu 
Would you try 'Europe/Istanbul' as `default_timezone` ?

**Comment by Eruhanu** [comment]
Actually, I was not sure whether it works or not because ,in Turkey, we were using 2 timezones (+0200 and +0300) depending on summer or winter terms until 2-3 years ago and we have used just +0300 for 2-3 years. We had some complicated changes in our timezone :)

But it works fine. Thank you very much :):):)
