### ISSUE TITLE
Could you tag 0.12.3?

### ISSUE THREAD

**Issue by civitaspo** [embulk/embulk-input-jdbc#227]
I find embulk-input-jdbc `0.12.3` on maven. https://mvnrepository.com/artifact/org.embulk/embulk-input-jdbc/0.12.3
But, this repository does not have the tag `0.12.3`. So could you tag 0.12.3?

**Comment by dmikurube** [comment]
Sorry! I forgot to push the tag. It's now there: https://github.com/embulk/embulk-input-jdbc/releases/tag/v0.12.3
