### ISSUE TITLE
embulk-input-oracle

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-input-jdbc#240]
So oracle support was removed from this repository. Has it moved to some external repo or what's the future for it?

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

https://github.com/embulk/embulk-input-jdbc/blob/1123a2d9ffc2a11ef5564c0538c73ccbeae598ae/ChangeLog#L15

There are no maintainers yet.

**Comment by kakoni** [comment]
I can help with the oracle input. Is it necessary to move it to external repo?

**Comment by hiroyuki-sato** [comment]
You need RubyGem's permission if manage that plugin. I'm not the owner of this plugin.
@dmikurube Could you comment?

Anyway, you can build that plugin from this repository. See also #223

**Comment by dmikurube** [comment]
Also see : https://github.com/embulk/embulk-input-jdbc/pull/206#issuecomment-846845438

Let's talk with @hito4t.

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

@hito4t (The author of embulk-input-oracle) created [embulk-input-jdbc-external](https://github.com/hito4t/embulk-input-jdbc-external) repo.
It contains `embulk-input-oracle`.
