### ISSUE TITLE
Unable to gem install a specific version of embulk-input-mysql. (>= 0.11.0)

### ISSUE THREAD

**Issue by fl-bunya** [embulk/embulk-input-jdbc#252]
## SUMMARY
I am currently unable to install a specific version of embulk-input-mysql (>= 0.11.0).
Last year in July, I was able to install version 0.13.0 using `gem install embulk-input-mysql:0.13.0`

Can anyone fix this issue?

## Attempts and Results

- Failed (0.13.2)
```
gem install embulk-input-mysql -v 0.13.2
ERROR:  Could not find a valid gem 'embulk-input-mysql' (= 0.13.2) in any repository
ERROR:  Possible alternatives: embulk-input-mysql
```

- Failed (0.13.2-java)
```
gem install embulk-input-mysql -v '0.13.2-java'
ERROR:  Could not find a valid gem 'embulk-input-mysql' (= 0.13.2.pre.java) in any repository
ERROR:  Possible alternatives: embulk-input-mysql
```

- Succeeded (no version specified, the latest version was installed)
```
gem install embulk-input-mysql
Successfully installed embulk-input-mysql-0.13.2-java
1 gem installed
```

- Succeeded (version 0.10.0)
```
gem install embulk-input-mysql -v '0.10.0'
Successfully installed embulk-input-mysql-0.10.0
1 gem installed
```

## Confirmed

- The current gem source repository
```
gem source
*** CURRENT SOURCES ***

https://rubygems.org/
```

- Available versions for installation
```
gem list embulk-input-mysql -rea

*** REMOTE GEMS ***

embulk-input-mysql (0.13.2 java
 0.13.1-java
 0.13.0-java
 0.12.4 java
 0.12.3 java
 0.12.2 java
 0.12.1 java
 0.12.0 java
 0.11.1 java
 0.11.0 java
 0.10.1
 0.10.0
 0.9.3
 0.9.2
 ...
```

- Downloadable gem
https://api.rubygems.org/gems/embulk-input-mysql-0.13.0-java.gem
https://api.rubygems.org/gems/embulk-input-mysql-0.10.0.gem

## Potential workaround
NOTE: I haven't tried this workaround yet.
Download the specific gem file and then install local gem file.
```
gem install --local embulk-input-mysql-0.13.0-java
```

**Comment by hiroyuki-sato** [comment]
Hello, @fl-bunya 

Your error may relate to the following.

* [RubyGems.org Dependency API Deprecation](https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html)
* [Dependency API Deprecation Delayed](https://blog.rubygems.org/2023/04/07/dependency-api-deprecation-delayed.html)

## How to fix the error 

### Plan1 Use v0.11

The latest stable release v0.11 had been released on 2023-06-13. Please read and try it.
[Embulk v0.11 is coming soon](https://www.embulk.org/articles/2023/04/13/embulk-v0.11-is-coming-soon.html).

### Plan v0.9

Create a `Gemfile` like the one below and execute `embulk bundle` in that directory.
This is almost the same as your Potential workaround.
`gem install --local embulk-input-mysql-0.13.0-java`

```ruby
source 'https://rubygems.org'

gem "embulk-input-mysql", "= 0.13.2"
```

## Reference

* [embulk gem (v0.9.x)でプラグインが見つからない、あるはずなのに..そんな時は](https://zenn.dev/hiroysato/articles/16f84886524a3d) (Japanese article)

**Comment by fl-bunya** [comment]
Hi, @hiroyuki-sato -san

Thank you for your polite and prompt reply.
It works.

```
echo "source 'https://rubygems.org'\n\ngem 'embulk-input-mysql', '= 0.13.2'" > Gemfile && embulk bundle install
```

ありがとうございました！
