### ISSUE TITLE
embulk-input-postgres: WHERE clause produces nothing in mode:merge

### ISSUE THREAD

**Issue by strife25** [embulk/embulk-input-jdbc#40]
I am trying to configure embulk to migrate data from one postgres database to another postgres database.

embulk-input-postgres and embulk-output-postgres works great when no WHERE clause is configured. However, when I add a WHERE clause to my input configuration and my output configuration uses `mode:merge`, nothing is updated in the output table.

If I remove the WHERE clause and migrate all of my data over, the merge mode works as expected and updates existing rows.

Here is my configuration:

```
in:
    type: postgresql
    host: localhost
    user: redacted
    password: redacted
    database: redacted
    table: redacted_table
    where: "modified >= '2016-03-1 22:20' OR deleted >= '2016-03-1 22:20'"
    column_options:
      id: {
        type: string,
        value_type: string
      }
      created_by: {
        type: string,
        value_type: string
      }
      user_id: {
        type: string,
        value_type: string
      }
out:
    type: postgresql
    host: localhost
    user: redacted
    database: embulkoutput
    table: redacted
    mode: merge
    merge_keys: ["id"]
```

If it helps at all, the the columns defined in the `column_options` parameter are UUID columns in the source database and to get embulk to work correctly, I need to set the above parameters to convert them into `string` types. This issue is out of scope for this bug, but I am not sure if it is part of the issue.

**Comment by hito4t** [comment]
Hi

We should clarify whether the problem is caused by the embulk-input-postresql side or embulk-output-postgresql side.

Would you output record to csv file instead of database?
If no record is written, the problem must be caused by the embulk-input-postresql side.

You can do easily by the following yml.
<pre>
...
out:
  type: file
  path_prefix: temp/output
  file_ext: csv
  formatter:
    type: csv
</pre>

**Comment by strife25** [comment]
So it looks like the problem was due to a timezone issue between the source database and the machine running embulk.

The source database was storing data in the native UTC timezone (+00), so my where clause was using that information. However, if I changed the WHERE clause to accommodate the time of my local machine (which is in CST at -0600) like so:

`where: "modified >= '2016-03-1 16:20' OR deleted >= '2016-03-1 16:20'"`

everything worked as expected.

This quality was not really apparent to me and is not defined in the docs at all. How can I configure the postgres input plugin to query for times according to how they are defined in UTC instead of my local machine's timezone? I would prefer to use my original query since all of my source databases store timestamps in native UTC times.

**Comment by hiroyuki-sato** [comment]
@strife25 

If server timezone set to UTC, all of date will treat as UTC.
As far as I know, It is PostgreSQL limitation. 

How about this query?

```
where: "modified >= DATE '2016-03-1 22:20' AT TIME ZONE 'CST' OR deleted >= '2016-03-1 22:20' AT TIME ZONE 'CST'"
```

P.S.

embulk-input-postgres has default_timzone parameter, but in this case, you can't use this parameter.

**Comment by strife25** [comment]
The above example did not work, but if I change the time zone argument to `UTC` in that statement it works:

```
where: "modified >= '2016-03-1 22:20' AT TIME ZONE 'UTC' OR deleted >= '2016-03-1 22:20' AT TIME ZONE 'UTC'"
```

Since this is a PostgreSQL problem, it might be worth to document this nuanced detail, but that may just may be me due to being a novice with complex SQL queries.

Thanks for the help - this is great!

**Comment by hito4t** [comment]
Thank you for the comment.

As you wrote, we should create more useful documents...
