### ISSUE TITLE
[Feature Request] Want to configure common type conversion options for all columns

### ISSUE THREAD

**Issue by sonots** [embulk/embulk-input-jdbc#41]
With `column_options`, we have to configure type conversion for each columns. If new columns are added, we have to change configuration manually. It is burdensome. 

What about to add new options like `type_options` such as:

```
type_options:
  DATE: {value_type: "date", type: "string", timestamp_format: "%Y-%m-%d", timezone: "Asia/Tokyo"}
```

so that we can fetch all DATE columns as a string rather than timestamp.

**Comment by hiroyuki-sato** [comment]
👍
I saw same request at yesterday.
https://twitter.com/yoyama/status/707866070514671616
(Japanese text)

**Comment by hito4t** [comment]
#45 has been merged.

**Comment by sonots** [comment]
Cool. Waiting to be released :)
