### ISSUE TITLE
`gradlew gem` fails in Windows

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-input-jdbc#42]
`gradlew gem` fails in Windows with the following error.
<pre>
Invalid gemspec in [xxx\embulk-input-jdbc\embulk-input-oracle\build\gemspec]: No such file or directory - git
ERROR:  Error loading gemspec. Aborting.
</pre>

It works in Cygwin.

**Comment by frsyuki** [comment]
gemspec file includes this line:
```
  spec.files         = `git ls-files`.split("\n") + Dir["classpath/*.jar"]
```

this executes `git` command and gets its result.
I think your windows environment doesn't have git in PATH.

**Comment by hito4t** [comment]
git exists in PATH.
If not, it won't work also in Cygwin.

It works when specifying git in full path.
<pre>
  spec.files         = `C:\\xxx\\xxx\\...\\Git\\cmd\\git ls-files`.split("\n") + Dir["classpath/*.jar"]
</pre>

**Comment by hito4t** [comment]
This is a bug in the older version of gradle.
Gradle returned 'PATH' as path variable name instead of correct name 'Path'.
jruby-gradle plugin pass a empty path to JRuby, and JRuby cannot find git.

The bug is already fixed.
https://github.com/gradle/gradle/commit/e6c3b16458fd8c087fa3302f9445ec4e375fae2b

**Comment by hito4t** [comment]
This is a bug in the older version (0.1.5) of jruby-gradle plugin.
JRubyExec class in jruby-gradle plugin get path by name 'PATH', but it should be 'Path' in Windows.
<pre>
        environment 'GEM_HOME' : gemDir,
                    'PATH' : getComputedPATH(System.env.PATH)
</pre>
jruby-gradle plugin pass a empty path to JRuby, and JRuby cannot find git.

This problem was already fixed.
We should use newer version of jruby-gradle plugin.
