### ISSUE TITLE
Bundle Microsoft SQL Server JDBC Driver

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-input-jdbc#84]
Open sourced!
https://blogs.msdn.microsoft.com/jdbcteam/2016/11/17/open-source-jdbc-maven/

**Comment by muga** [comment]
It seems that the driver requires Java 8 according to https://github.com/Microsoft/mssql-jdbc/blob/master/README.md. We need to move forward to upgrade Java version for Embulk.

**Comment by hito4t** [comment]
This issue is resolved by the PR #164 .
