### ISSUE TITLE
Incremental column support for timestamps in Oracle

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-input-jdbc#96]
Thinking timestamps here.

**Comment by hiroyuki-sato** [comment]
Do you want to use timestamp column for incremental load?
What is the RDBMS?

How about #79 #89 ?

**Comment by kakoni** [comment]
Yes, but but for oracle. I'll have have look at #79 and #89, perhaps I can submit a pull request. Changed the title also to more approriate.

**Comment by kakoni** [comment]
Ok, https://github.com/embulk/embulk-input-jdbc/pull/99

**Comment by kakoni** [comment]
Closing as this was merged
